require 'bundler'
require 'rspec/core/rake_task'
require 'jenkins/war'
require 'rake/clean'

class Bundler::GemHelper
  def version_tag
    "runtime-v#{version}"
  end
  install_tasks
end

RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--color --fail-fast'
end
task :spec => :compile

Jenkins::War.classpath
ClassPath =  FileList[File.join(ENV['HOME'], '.jenkins', 'wars', Jenkins::War::VERSION, "**/*.jar")].to_a.join(':')

desc "compile java source code"
task "compile" => "target" do
  sh "javac -classpath #{ClassPath} #{FileList['src/**/*.java']} -d target"
end

directory "target"
CLEAN.include("target")

task :default => [:compile, :spec]
